version: '3'

services:

  proxy:
    build: ./proxy
    
    networks:
      - internal
    ports:
      - '8080:8080'
      - '8081:8081'

  vote:
    build: ./vote
    
    depends_on:
      - redis
      - proxy
    volumes:
     - ./vote:/app
    networks:
      - internal

  result:
    build: ./result

    depends_on:
      - db
      - proxy
    volumes:
      - ./result:/app
    ports:
      - '5858:5858'
    networks:
      - internal

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - internal

  redis:
    image: redis:5.0-alpine3.10
    ports: ['6379']
    networks:
      - internal

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    networks:
      - internal

volumes:
  db-data:

networks:
  internal:
